# Generated by Django 4.2.6 on 2023-10-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(blank=True, max_length=50)),
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('contacto', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('eps', models.CharField(blank=True, max_length=30)),
                ('genero', models.CharField(blank=True, max_length=20)),
                ('usuario', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(blank=True, max_length=20)),
                ('name_emergencia', models.CharField(blank=True, max_length=50)),
                ('contacto_emergencia', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
